#ifndef _ERRORS_H
#define _ERRORS_H

#include <errno.h>

#define TIMECALL_FAILCODE 1
#define LOADAVG_FAILCODE 2
#define SHMGET_FAILCODE 3
#define SHMAT_FAILCODE 4
#define SEMINIT_FAILCODE 5
#define SEMGET_FAILCODE 6
#define SEMOP_FAILCODE 7
#define SOCKET_FAILCODE 8
#define CONNECT_FAILCODE 9
#define READ_FAILCODE 10
#define BIND_FAILCODE 11
#define LISTEN_FAILCODE 12

#endif
