#!/bin/bash

panic() {
	echo "$1" >&2
	exit $2
}

directory="$PWD"

if (( $# > 0 ));
then
	directory="$1"
fi

if [ -d "$directory" ];
then
	cd "$directory" || panic "Could not cd." 2
else
	>&2 echo "Usage: writepipe [directory]
	directory -- directory where to check the open fifos
	if directory is omitted, pwd is used"
	exit 1
fi

gfind . -type p -exec bash -c 'for proc in `fuser "$1" 2>/dev/null`; do FID=`ls -i "$1" | awk -f awkscript`; pfiles $proc | ggrep -A2 "$FID" | ggrep -A2 "S_IFIFO" | ggrep -A1 "O_RDWR" >/dev/null && exit 0; done; exit 1' _ {} \; -print
